"""Initial schema: Create all tables in public schema

Revision ID: 8fcdb09189dd
Revises:
Create Date: 2025-11-10 00:51:35.835288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '8fcdb09189dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('stage_tag', sa.String(length=100), nullable=True),
    sa.Column('affinity_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_user', 'dialogue_turns', ['session_id', 'user_id'], unique=False)
    op.create_index('idx_user_created', 'dialogue_turns', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dialogue_turns_session_id'), 'dialogue_turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_dialogue_turns_user_id'), 'dialogue_turns', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('entity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("entity_type IN ('character', 'location', 'event', 'item', 'skill')", name='valid_entity_type'),
    sa.CheckConstraint('importance_score >= 0.0 AND importance_score <= 1.0', name='valid_importance'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('entity_type', 'canonical_name')
    )
    op.create_index('idx_entities_canonical_name', 'entities', ['canonical_name'], unique=False)
    op.create_index('idx_entities_community', 'entities', ['community_id'], unique=False)
    op.create_index('idx_entities_importance', 'entities', ['importance_score'], unique=False)
    op.create_index('idx_entities_mention_count', 'entities', ['mention_count'], unique=False)
    op.create_index('idx_entities_type', 'entities', ['entity_type'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index('idx_password_reset_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('idx_password_reset_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_index('idx_password_reset_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_bubbles', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('entity_relationships',
    sa.Column('relationship_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('strength >= 0.0 AND strength <= 1.0', name='valid_strength'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'relationship_type')
    )
    op.create_index('idx_relationships_source', 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index('idx_relationships_strength', 'entity_relationships', ['strength'], unique=False)
    op.create_index('idx_relationships_target', 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_index('idx_relationships_type', 'entity_relationships', ['relationship_type'], unique=False)
    op.create_table('scenario_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('char_length(content) >= 1 AND char_length(content) <= 1000'),
    sa.CheckConstraint('like_count >= 0'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['scenario_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scenario_comments_parent', 'scenario_comments', ['parent_comment_id'], unique=False)
    op.create_index('idx_scenario_comments_scenario', 'scenario_comments', ['scenario_id', 'created_at'], unique=False)
    op.create_index('idx_scenario_comments_scenario_likes', 'scenario_comments', ['scenario_id', 'like_count'], unique=False)
    op.create_index(op.f('ix_scenario_comments_scenario_id'), 'scenario_comments', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_comments_user_id'), 'scenario_comments', ['user_id'], unique=False)
    op.create_table('scenario_likes',
    sa.Column('like_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('scenario_id', 'user_id', name='scenario_likes_unique')
    )
    op.create_index('idx_scenario_likes_scenario', 'scenario_likes', ['scenario_id', 'created_at'], unique=False)
    op.create_index('idx_scenario_likes_user', 'scenario_likes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scenario_likes_scenario_id'), 'scenario_likes', ['scenario_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('current_stage', sa.String(length=255), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('stage_turn', sa.Integer(), nullable=True),
    sa.Column('final_ending', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('summary_updated_at', sa.DateTime(), nullable=True),
    sa.Column('summary_turn_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_sessions_created', 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_is_active'), 'sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_sessions_scenario_id'), 'sessions', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_character_affinity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('total_affinity_score', sa.Integer(), nullable=False),
    sa.Column('affinity_level', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('affinity_level >= 1 AND affinity_level <= 10'),
    sa.CheckConstraint('total_affinity_score >= 0 AND total_affinity_score <= 1000'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_name')
    )
    op.create_index('idx_user_character_affinity_character', 'user_character_affinity', ['character_name'], unique=False)
    op.create_index('idx_user_character_affinity_score', 'user_character_affinity', ['user_id', 'total_affinity_score'], unique=False)
    op.create_index(op.f('ix_user_character_affinity_user_id'), 'user_character_affinity', ['user_id'], unique=False)
    op.create_table('user_memories',
    sa.Column('memory_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("memory_type IN ('episodic', 'semantic', 'procedural')", name='valid_memory_type'),
    sa.CheckConstraint('importance_score >= 0.0 AND importance_score <= 1.0', name='valid_memory_importance'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('idx_memories_importance', 'user_memories', ['importance_score'], unique=False)
    op.create_index('idx_memories_scenario', 'user_memories', ['scenario_id'], unique=False)
    op.create_index('idx_memories_type', 'user_memories', ['memory_type'], unique=False)
    op.create_index('idx_memories_user', 'user_memories', ['user_id', 'created_at'], unique=False)
    op.create_table('affinity_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('affinity_score', sa.Integer(), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_affinity_character', 'affinity_records', ['character_name'], unique=False)
    op.create_index('idx_affinity_session', 'affinity_records', ['session_id', 'character_name'], unique=False)
    op.create_index('idx_affinity_timestamp', 'affinity_records', ['timestamp'], unique=False)
    op.create_table('comment_likes',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['scenario_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_index('idx_comment_likes_comment', 'comment_likes', ['comment_id'], unique=False)
    op.create_index('idx_comment_likes_user', 'comment_likes', ['user_id'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('mention_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('mention_text', sa.Text(), nullable=True),
    sa.Column('context_window', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('mentioned_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('sentiment_score >= -1.0 AND sentiment_score <= 1.0', name='valid_sentiment'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mention_id')
    )
    op.create_index('idx_mentions_entity', 'entity_mentions', ['entity_id', 'mentioned_at'], unique=False)
    op.create_index('idx_mentions_session', 'entity_mentions', ['session_id', 'turn_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mentions_session', table_name='entity_mentions')
    op.drop_index('idx_mentions_entity', table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index('idx_comment_likes_user', table_name='comment_likes')
    op.drop_index('idx_comment_likes_comment', table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index('idx_affinity_timestamp', table_name='affinity_records')
    op.drop_index('idx_affinity_session', table_name='affinity_records')
    op.drop_index('idx_affinity_character', table_name='affinity_records')
    op.drop_table('affinity_records')
    op.drop_index('idx_memories_user', table_name='user_memories')
    op.drop_index('idx_memories_type', table_name='user_memories')
    op.drop_index('idx_memories_scenario', table_name='user_memories')
    op.drop_index('idx_memories_importance', table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_user_character_affinity_user_id'), table_name='user_character_affinity')
    op.drop_index('idx_user_character_affinity_score', table_name='user_character_affinity')
    op.drop_index('idx_user_character_affinity_character', table_name='user_character_affinity')
    op.drop_table('user_character_affinity')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_scenario_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_active'), table_name='sessions')
    op.drop_index('idx_sessions_created', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_scenario_likes_scenario_id'), table_name='scenario_likes')
    op.drop_index('idx_scenario_likes_user', table_name='scenario_likes')
    op.drop_index('idx_scenario_likes_scenario', table_name='scenario_likes')
    op.drop_table('scenario_likes')
    op.drop_index(op.f('ix_scenario_comments_user_id'), table_name='scenario_comments')
    op.drop_index(op.f('ix_scenario_comments_scenario_id'), table_name='scenario_comments')
    op.drop_index('idx_scenario_comments_scenario_likes', table_name='scenario_comments')
    op.drop_index('idx_scenario_comments_scenario', table_name='scenario_comments')
    op.drop_index('idx_scenario_comments_parent', table_name='scenario_comments')
    op.drop_table('scenario_comments')
    op.drop_index('idx_relationships_type', table_name='entity_relationships')
    op.drop_index('idx_relationships_target', table_name='entity_relationships')
    op.drop_index('idx_relationships_strength', table_name='entity_relationships')
    op.drop_index('idx_relationships_source', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_user_id', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_token', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_expires_at', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_entities_type', table_name='entities')
    op.drop_index('idx_entities_mention_count', table_name='entities')
    op.drop_index('idx_entities_importance', table_name='entities')
    op.drop_index('idx_entities_community', table_name='entities')
    op.drop_index('idx_entities_canonical_name', table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_dialogue_turns_user_id'), table_name='dialogue_turns')
    op.drop_index(op.f('ix_dialogue_turns_session_id'), table_name='dialogue_turns')
    op.drop_index('idx_user_created', table_name='dialogue_turns')
    op.drop_index('idx_session_user', table_name='dialogue_turns')
    op.drop_table('dialogue_turns')
    # ### end Alembic commands ###
