"""Initial migration: create dialogue_turns table

Revision ID: 467a802d571c
Revises: 
Create Date: 2025-11-07 16:07:45.465484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467a802d571c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('stage_tag', sa.String(length=100), nullable=True),
    sa.Column('affinity_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_user', 'dialogue_turns', ['session_id', 'user_id'], unique=False)
    op.create_index('idx_user_created', 'dialogue_turns', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dialogue_turns_session_id'), 'dialogue_turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_dialogue_turns_user_id'), 'dialogue_turns', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_turns_user_id'), table_name='dialogue_turns')
    op.drop_index(op.f('ix_dialogue_turns_session_id'), table_name='dialogue_turns')
    op.drop_index('idx_user_created', table_name='dialogue_turns')
    op.drop_index('idx_session_user', table_name='dialogue_turns')
    op.drop_table('dialogue_turns')
    # ### end Alembic commands ###
