"""Add gallery_images table

Revision ID: 14260dbfb3e6
Revises: 8fcdb09189dd
Create Date: 2025-11-10 01:04:51.059031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14260dbfb3e6'
down_revision = '8fcdb09189dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('stage_tag', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=False),
    sa.Column('generation_prompt', sa.String(length=2000), nullable=True),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index('idx_gallery_scenario_id', 'gallery_images', ['scenario_id'], unique=False)
    op.create_index('idx_gallery_session_id', 'gallery_images', ['session_id'], unique=False)
    op.create_index('idx_gallery_user_id', 'gallery_images', ['user_id'], unique=False)
    op.create_index('idx_gallery_user_scenario', 'gallery_images', ['user_id', 'scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gallery_user_scenario', table_name='gallery_images')
    op.drop_index('idx_gallery_user_id', table_name='gallery_images')
    op.drop_index('idx_gallery_session_id', table_name='gallery_images')
    op.drop_index('idx_gallery_scenario_id', table_name='gallery_images')
    op.drop_table('gallery_images')
    # ### end Alembic commands ###
